leapt_admin_default_index:
    path:     ""
    defaults: { _controller: LeaptAdminBundle:Default:index }

leapt_admin_reorderablecontent_reorder:
    path:     /reorder/{code}/{locale}
    defaults: { _controller: LeaptAdminBundle:ReorderableContent:reorder, locale: null }

leapt_admin_markdown:
    path:     /markdown
    defaults: { _controller: LeaptAdminBundle:Default:markdown }

leapt_admin_switch_locale:
    path:     /switch-locale/{locale}
    defaults: { _controller: LeaptAdminBundle:Default:switchLocale }

leapt_admin_wysiwyg_browser:
    path:     /wysiwyg/browser
    defaults: { _controller: LeaptAdminBundle:Wysiwyg:browser }

leapt_admin_cataloguetranslation_index:
    path:     /catalogue-translation/{catalogue}/{locale}
    defaults: { _controller: LeaptAdminBundle:CatalogueTranslation:index, catalogue: messages, locale: null }

leapt_admin_widget_delete_item:
    path:     /widget/delete-item
    defaults: { _controller: LeaptAdminBundle:Widget:deleteItem }

leapt_admin_widget_content_changed:
    path:     /widget/content-changed
    defaults: { _controller: LeaptAdminBundle:Widget:contentChanged }

leapt_admin_upload:
    path:     /upload
    defaults: { _controller: LeaptAdminBundle:Upload:upload }

leapt_admin_login:
    path:     /login
    defaults:  { _controller: LeaptAdminBundle:Security:login }

leapt_admin_login_check:
    path:     /login_check

leapt_admin_logout:
    path:     /logout

leapt_admin_extra:
    resource: .
    type: leapt_admin_extra