parameters:
    leapt_admin.logger_entity.class: Leapt\AdminBundle\Entity\Log
    leapt_admin.security.user_class: ~
    leapt_admin.translation_catalogues: ~
    leapt_admin.multiupload.tmp_dir: ~

services:
    # Main admin class
    leapt_admin:
        class: Leapt\AdminBundle\AdminManager
        public: true

    # Base admin services
    leapt_admin.admin_abstract:
        class: Leapt\AdminBundle\Admin\AbstractAdmin
        abstract: true
        calls:
            - [ setContainer, [ "@service_container" ]]
            - [ setDatalistFactory, [ '@Leapt\CoreBundle\Datalist\DatalistFactory' ]]

    leapt_admin.admin_content:
        class: Leapt\AdminBundle\Admin\ContentAdmin
        abstract: true
        parent: leapt_admin.admin_abstract

    # Routing
    leapt_admin.routing_loader:
        class: Leapt\AdminBundle\Routing\Loader\AdminLoader
        arguments: [ "@leapt_admin" ]
        tags:
            - { name: routing.loader }

    leapt_admin.routing_helper_content:
        class: Leapt\AdminBundle\Routing\Helper\ContentRoutingHelper
        arguments: [ "@router", "@controller_name_converter", "", "" ]
        public: true

    # Param converters
    leapt_admin.param_converter:
        class: Leapt\AdminBundle\Request\ParamConverter\AdminParamConverter
        arguments: [ "@leapt_admin", "@leapt_core.navigation" ]
        tags:
            - { name: request.param_converter }

    # Event listeners
    leapt_admin.listener_logger:
        class: Leapt\AdminBundle\EventListener\LoggerListener
        arguments: [ "@leapt_admin.logger" ]
        tags:
            - { name: kernel.event_subscriber }

    # Twig extensions and loaders
    leapt_admin.twig_admin:
        class: Leapt\AdminBundle\Twig\Extension\AdminExtension
        arguments: [ "@leapt_admin", "@leapt_admin.routing_helper_content", "@translator" ]
        tags:
            -  { name: twig.extension }

    leapt_admin.twig_loader:
        class: Leapt\AdminBundle\Twig\Loader\AdminLoader
        arguments: [ "@templating.locator", "@templating.name_parser" ]
        tags:
            - { name: twig.loader }

    # Form types
    leapt_admin.form_type_entity:
        class: Leapt\AdminBundle\Form\Type\EntityType
        arguments: [ "@leapt_admin", "@leapt_admin.routing_helper_content" ]
        tags:
            - { name: form.type, alias: leapt_admin_entity }

    leapt_admin.form_type_autocomplete:
        class: Leapt\AdminBundle\Form\Type\AutocompleteType
        arguments: [ "@leapt_admin", "@leapt_admin.routing_helper_content" ]
        tags:
            -  { name: form.type }

    leapt_admin.form_type_multiupload:
        class: Leapt\AdminBundle\Form\Type\MultiUploadType
        arguments: [ "%kernel.root_dir%" ]
        tags:
            -  { name: form.type, alias: leapt_admin_multiupload }

    leapt_admin.form_type_multiupload_url:
        class: Leapt\AdminBundle\Form\Type\MultiUploadUrlType
        tags:
            -  { name: form.type, alias: leapt_admin_multiupload_url }

    leapt_admin.form_type_multiupload_image:
        class: Leapt\AdminBundle\Form\Type\MultiUploadImageType
        tags:
            -  { name: form.type, alias: leapt_admin_multiupload_image }

    # Form type extensions
    leapt_admin.form_extension_collection:
        class: Leapt\AdminBundle\Form\Extension\CollectionTypeExtension
        arguments: [ "@router" ]
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\CollectionType }

    leapt_admin.form_extension_text:
        class: Leapt\AdminBundle\Form\Extension\TextTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\TextType }

    # Datalists
    Leapt\AdminBundle\Datalist\Action\Type\ContentAdminActionType:
        arguments: [ "@leapt_admin", "@leapt_admin.routing_helper_content" ]
        tags:
            - { name: leapt_core.datalist.action_type, alias: content_admin }

    # Admin logger
    leapt_admin.logger:
        class: Leapt\AdminBundle\Logger\Logger
        arguments: [ "@leapt_admin", "@doctrine.orm.entity_manager", "@security.token_storage", "@security.authorization_checker", "%leapt_admin.logger_entity.class%" ]

    # Security
    leapt_admin.security.user_manager:
        class: Leapt\AdminBundle\Security\UserManager
        arguments: [ "%leapt_admin.security.user_class%", "@security.encoder_factory", "@doctrine.orm.entity_manager" ]

    leapt_admin.content_voter:
        class: Leapt\AdminBundle\Security\Voter\ContentAdminVoter
        public: false
        arguments: [ "@leapt_admin" ]
        tags:
            - { name: security.voter }
