parameters:
    leapt_admin.logger_entity.class: Leapt\AdminBundle\Entity\Log
    leapt_admin.security.user_class: ~
    leapt_admin.translation_catalogues: ~
    leapt_admin.multiupload.tmp_dir: ~

services:
    # Main admin class
    leapt_admin:
        class: Leapt\AdminBundle\AdminManager

    # Base admin services
    leapt_admin.admin_abstract:
        class: Leapt\AdminBundle\Admin\AbstractAdmin
        abstract: true
        calls:
            - [ setContainer, [ "@service_container" ]]

    leapt_admin.admin_content:
        class: Leapt\AdminBundle\Admin\ContentAdmin
        abstract: true
        parent: leapt_admin.admin_abstract

    # Routing
    leapt_admin.routing_loader:
        class: Leapt\AdminBundle\Routing\Loader\AdminLoader
        arguments: [ "@leapt_admin" ]
        tags:
            - { name: routing.loader }

    leapt_admin.routing_helper_content:
        class: Leapt\AdminBundle\Routing\Helper\ContentRoutingHelper
        arguments: [ "@router", "@controller_name_converter", "", "" ]

    # Param converters
    leapt_admin.param_converter:
        class: Leapt\AdminBundle\Request\ParamConverter\AdminParamConverter
        arguments: [ "@leapt_admin", "@leapt_core.navigation" ]
        tags:
            - { name: request.param_converter }

    # Event listeners
    leapt_admin.listener_logger:
        class: Leapt\AdminBundle\EventListener\LoggerListener
        arguments: [ "@leapt_admin.logger" ]
        tags:
            - { name: kernel.event_subscriber }

    # Twig extensions and loaders
    leapt_admin.twig_admin:
        class: Leapt\AdminBundle\Twig\Extension\AdminExtension
        arguments: [ "@leapt_admin", "@leapt_admin.routing_helper_content", "@translator" ]
        tags:
            -  { name: twig.extension }

    leapt_admin.twig_datalist:
        class: Leapt\AdminBundle\Twig\Extension\DatalistExtension
        arguments: [ "@form.factory" ]
        calls:
            - [ setContainer, [ "@service_container" ]]
        tags:
            -  { name: twig.extension }
    leapt_admin.twig_loader:
        class: Leapt\AdminBundle\Twig\Loader\AdminLoader
        arguments: [ "@templating.locator", "@templating.name_parser" ]
        tags:
            - { name: twig.loader }

    # Form types
    leapt_admin.form_type_entity:
        class: Leapt\AdminBundle\Form\Type\EntityType
        arguments: [ "@leapt_admin", "@leapt_admin.routing_helper_content" ]
        tags:
            - { name: form.type, alias: leapt_admin_entity }

    leapt_admin.form_type_autocomplete:
        class: Leapt\AdminBundle\Form\Type\AutocompleteType
        arguments: [ "@leapt_admin", "@leapt_admin.routing_helper_content" ]
        tags:
            -  { name: form.type }

    leapt_admin.form_type_multiupload:
        class: Leapt\AdminBundle\Form\Type\MultiUploadType
        arguments: [ %kernel.root_dir% ]
        tags:
            -  { name: form.type, alias: leapt_admin_multiupload }

    leapt_admin.form_type_multiupload_url:
        class: Leapt\AdminBundle\Form\Type\MultiUploadUrlType
        tags:
            -  { name: form.type, alias: leapt_admin_multiupload_url }

    leapt_admin.form_type_multiupload_image:
        class: Leapt\AdminBundle\Form\Type\MultiUploadImageType
        tags:
            -  { name: form.type, alias: leapt_admin_multiupload_image }

    # Form type extensions
    leapt_admin.form_extension_collection:
        class: Leapt\AdminBundle\Form\Extension\CollectionTypeExtension
        arguments: [ "@router" ]
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\CollectionType }

    leapt_admin.form_extension_text:
        class: Leapt\AdminBundle\Form\Extension\TextTypeExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\TextType }

    # Datalists
    leapt_admin.datalist_factory:
        class: Leapt\AdminBundle\Datalist\DatalistFactory
        arguments: [ "@form.factory" ]

    leapt_admin.datalist_type.datalist:
        class: Leapt\AdminBundle\Datalist\Type\DatalistType
        tags:
            - { name: leapt_admin.datalist_type, alias: datalist }

    leapt_admin.datalist_field_datetime:
        class: Leapt\AdminBundle\Datalist\Field\Type\DateTimeFieldType
        tags:
            - { name: leapt_admin.datalist_fieldtype, alias: datetime }

    leapt_admin.datalist_field_heading:
        class: Leapt\AdminBundle\Datalist\Field\Type\HeadingFieldType
        tags:
            - { name: leapt_admin.datalist_fieldtype, alias: heading }

    leapt_admin.datalist_field_image:
        class: Leapt\AdminBundle\Datalist\Field\Type\ImageFieldType
        tags:
            - { name: leapt_admin.datalist_fieldtype, alias: image }

    leapt_admin.datalist_field_label:
        class: Leapt\AdminBundle\Datalist\Field\Type\LabelFieldType
        tags:
            - { name: leapt_admin.datalist_fieldtype, alias: label }

    leapt_admin.datalist_field_boolean:
        class: Leapt\AdminBundle\Datalist\Field\Type\BooleanFieldType
        tags:
            - { name: leapt_admin.datalist_fieldtype, alias: boolean }

    leapt_admin.datalist_field_text:
        class: Leapt\AdminBundle\Datalist\Field\Type\TextFieldType
        tags:
            - { name: leapt_admin.datalist_fieldtype, alias: text }

    leapt_admin.datalist_field_url:
        class: Leapt\AdminBundle\Datalist\Field\Type\UrlFieldType
        parent: leapt_admin.datalist_field_text
        tags:
            - { name: leapt_admin.datalist_fieldtype, alias: url }

    leapt_admin.datalist_filter_choice:
        class: Leapt\AdminBundle\Datalist\Filter\Type\ChoiceFilterType
        tags:
            - { name: leapt_admin.datalist_filtertype, alias: choice }

    leapt_admin.datalist_filter_entity:
        class: Leapt\AdminBundle\Datalist\Filter\Type\EntityFilterType
        tags:
            - { name: leapt_admin.datalist_filtertype, alias: entity }

    leapt_admin.datalist_filter_search:
        class: Leapt\AdminBundle\Datalist\Filter\Type\SearchFilterType
        tags:
            - { name: leapt_admin.datalist_filtertype, alias: search }

    leapt_admin.datalist_action_simple:
        class: Leapt\AdminBundle\Datalist\Action\Type\SimpleActionType
        arguments: [ "@router" ]
        tags:
            - { name: leapt_admin.datalist_actiontype, alias: simple }

    leapt_admin.datalist_action_content_admin:
        class: Leapt\AdminBundle\Datalist\Action\Type\ContentAdminActionType
        arguments: [ "@leapt_admin", "@leapt_admin.routing_helper_content" ]
        tags:
            - { name: leapt_admin.datalist_actiontype, alias: content_admin }

    # Admin logger
    leapt_admin.logger:
        class: Leapt\AdminBundle\Logger\Logger
        arguments: [ "@leapt_admin", "@doctrine.orm.entity_manager", "@security.token_storage", "@security.authorization_checker", %leapt_admin.logger_entity.class% ]

    # Security
    leapt_admin.security.user_manager:
        class: Leapt\AdminBundle\Security\UserManager
        arguments: [ %leapt_admin.security.user_class%, "@security.encoder_factory", "@doctrine.orm.entity_manager" ]

    leapt_admin.content_voter:
        class: Leapt\AdminBundle\Security\Voter\ContentAdminVoter
        public: false
        arguments: [ "@leapt_admin" ]
        tags:
            - { name: security.voter }
